# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    macos:
      xcode: "10.1.0"

    steps:
      - checkout

  test:

    # Specify the Xcode version to use
    macos:
      xcode: "10.1.0"

    steps:
      # Build the app and run tests
      - run:
          name: Tests
          command: ./Scripts/test

workflow:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
